오각형 변수 분석 API
HANIUM-GROWUP/growthmate-be pull request #18
Opened 2023-09-18 01:08 UTC by Jeongh00

## 📌 작업 내용
- 오각형 변수 분석 조회 api 개발 완료.
- 간단 조회 작업이라 mapstruct 를 통해 dto mapping 자동화
- company 관련 sql 파일 새로 생성

## 📝 리뷰 요청
- 오타 혹은 불필요한 로직 등 부족한 부분 리뷰 부탁드립니다.

2023-09-18 05:44 UTC, ldk980130 requested changes
사소한 피드백 여러가지랑 로직적인 피드백 한 가지를 남겨두었습니다. 수정하는데 오래 걸리진 않을거에요!

2023-09-18 05:44 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
> +    }
comany_id가 아니라 companyId로 camel case로 작성하면 좋을 것 같아요!

2023-09-18 05:44 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        return response;
이미 짧긴 하지만 response를 바로 리턴하면 코드가 더 짧아질 것 같아요.

인텔리제이가 표시하는 노란불 (warnning)을 확인하면 더 나은 코드를 작성하거나 오류 같은걸 발견할 수도 있으니 항상 확인해보면 좋아요!
<img width="613" alt="image" src="https://github.com/HANIUM-GROWUP/growthmate-be/assets/78652144/f8a34c72-6323-4b0a-a76a-c1181cd4577a">

2023-09-18 05:44 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/mapper/CompanyAnalysisMapper.java
> +    CompanyAnalysisResponse toAnalysisDTO(CompanyAnalysis companyAnalysis);
매핑 로직이 단순할 땐 mapstruct가 아주 유용할 것 같네요! 👍

2023-09-18 05:44 UTC, ldk980130 commented on growthmate-api/src/test/resources/company_fixture.sql
> +values (1, 1, 80, 70, 90, 50, 60);
개행 추가해주세요~

2023-09-18 05:44 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyAnalysisRepository.java
> +}
`companyId`로 오각형 분석 데이터를 찾는 인터페이스네요. 해당 `companyId`에 해당하는 데이터가 없거나 `companyId`가 잘못 되었을 경우 NPE가 발생할 것 같아요. `Optional`을 활용해서 예외 처리를 추가하면 어떨까요?

2023-09-18 08:43 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        return response;
넵! 감사합니다!^^

2023-09-20 05:33 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyAnalysisRepository.java
> +}
`CompanyException` 파일을 하나 새로 추가해 `Optional` 을 활용하여 예외처리 로직 추가하였습니다^^

2023-09-20 06:10 UTC, ldk980130 approved these changes
수고하셨습니다!

2023-09-20 06:10 UTC, merged