Feature/company select all
HANIUM-GROWUP/growthmate-be pull request #23
Opened 2023-10-06 02:29 UTC by Jeongh00

## 📌 작업 내용
스타트업 전체 목록 조회 api 개발 완료했습니다.
기존 페이징 컨벤션 활용한 상태에서 정렬 기준 추가했습니다.
테스트 케이스별로 모두 진행했습니다.
노션에 올라와있는 명세대로 개발 진행했습니다^^

## 📝 리뷰 요청
딱히 어려운 부분은 없었던 거 같은데 잘 되어있는지 확인해주세요~

2023-10-06 13:07 UTC, ldk980130 requested changes
기업 모두 조회 수고하셨습니다! 자잘한 네이밍 관련 코멘트도 포함해서 생각해볼만한 점 위주로 리뷰 남겼습니다.

충분히 생각해보고 피드백 반영하거나 답변 달아주세요!

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
> +        CompanySelectRequest request = new CompanySelectRequest(params.getCursor(), params.getSize(), sort);
sort가 없으면 예외가 발생하던데 이 경우 어떻게 예외처리를 해야할까요? sort가 없으면 400 에러만 발생하고 있어요. sort값은 필수라는 예외를 던지거나 기본 정렬을 설정하는게 좋을 것 같아요. 동적 쿼리를 사용하고 있으니 sort가 없으면 정렬을 안시킨채로 반환시키는 로직을 짜는 것도 방법이겠네요

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        }
리스트를 조회하는 로직에서 리스트가 비어 있으면 예외가 발생하나요? 그냥 빈 리스트([])를 반환하는게 자연스러운 것 같아요. 페이징을 하다가 마지막 페이지에 아무것도 없다고 해서 예외를 터뜨리지는 않듯이요.

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/dto/detail/CompanySelectResponse.java
> +public record CompanySelectResponse(
dto 이름을 이렇게 명명한 의도가 무엇인가요?

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/dto/detail/CompanySelectResponse.java
> +        LocalDateTime establishmentDate) {
<img width="367" alt="image" src="https://github.com/HANIUM-GROWUP/growthmate-be/assets/78652144/ca5f60c4-df4d-4042-a81b-dee0cc522cbb">

api 스펙이랑 다른데 수정해주세요!
- companyId가 빠져있어요. companyId는 커서 페이징에 사용되는 커서이기 때문에 필수로 보내주셔야 해요.
- establishmentDate는 정렬 조건에 사용되기는 하지만 실제로 반환해주지는 않습니다.

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        return companyAnalysisMapper.toAllSelectDTO(companies);
mapper의 이름이 어색하지 않나요? `toAllSelectDto`는 회사 정보를 간략하게 표현하는 dto로 변환하는 메서드에요. 그런데 클래스 이름이 `CompanyAnalysisMapper`면 오각형 분석에 관련한 데이터에 대한 책임만 있는 것처럼 보여요.

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/mapper/CompanyAnalysisMapper.java
> +    List<CompanySelectResponse> toAllSelectDTO(List<Company> company);
mapstruct를 쓰면 리스트간 매핑도 이렇게 간단하게 할 수 있군요 👍

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/detail/CompanyDetailRepository.java
> +
엄밀히 말하면 모든 회사를 가져오는건 아니라 `findAll`은 어색한 것 같아요. 그리고 이 인터페이스도 회사의 상세 정보만 가져오는 인터페이스가 아니게 되었는데 `CompanyDetailRepository`면 이름과 책임이 매칭이 안되고 있는 것 같아요.

클래스의 이름은 클래스의 역할과 책임을 함축하고 있어요. 클래스의 기능을 추가하거나 변경할 때 이름이 적절한지 한 번 생각해 보면 좋을 것 같아요.

코딩 특 이름 짓는게 어려움 😄

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/detail/CompanyDetailRepositoryImpl.java
> +        }
만약 정렬 기준이 변경되면 계속 이 if-else 문을 고쳐야겠죠? 만약 정렬 기준이 엄청 많다면 가독성도 떨어지고 코드도 비대해질 것 같아요. 

if-else 문을 지양하라라는 말이 많은데 왜 그런걸까요?

이 블로그 글을 한 번 읽어보고 if-else 문을 어떻게 개선할 수 있을지 생각해보면 좋을 것 같아요!
https://techblog.woowahan.com/2527/

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/detail/CompanyDetailRepositoryImpl.java
> +    public List<Company> findAllCompanies(CompanySelectRequest request) {
이 api에서 필요한 정보는 company의 약 10개 필드 중 4개에요. 다 가져오는면 필요 없는 데이터까지 가져오게 되지 않을까요?

물론 그냥 Company 엔티티로 다 가져오는게 코드양이 훨씬 줄긴 하죠. 그냥 이대로 놔둬도 지금은 괜찮을 것 같아요. 만약 성능을 신경써야하는 단계에서 최적화의 대상이 될 수는 있을텐데 어떻게 생각하시나요?

1. 개발하다가 성능 문제가 발생했을 때 고친다.
2. 처음부터 필요한 것만 가져오게 한다.

각각의 장단점이 있을 것 같은데 한 번 생각해보시고 한 방법을 선택해서 이유를 알려주면 좋을 것 같아요ㅎㅎ

2023-10-06 13:07 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
> +    class CompanyDetailInfoTest {
이 테스트가 실패하던데 한 번 확인해주세요~

2023-10-07 09:02 UTC, Jeongh00 commented on growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
> +    class CompanyDetailInfoTest {
data 를 수정하던 중 저 부분을 놓쳤네요. 수정했습니다.

2023-10-07 09:03 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
> +        CompanySelectRequest request = new CompanySelectRequest(params.getCursor(), params.getSize(), sort);
기본 정렬은 id 로 가져가게끔 하고, sort 가 있을때 해당 정렬로 되도록 수정했습니다~

2023-10-07 09:45 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        }
그렇네요. 그냥 예외 없이 빈 리스트로 리턴하도록 하겠습니다.

2023-10-07 09:46 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/dto/detail/CompanySelectResponse.java
> +public record CompanySelectResponse(
company 에 대해 조회해 온 결과를 담는 곳이라 저렇게 명명했는데, 의도가 불명확할까요...?

2023-10-07 09:47 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        return companyAnalysisMapper.toAllSelectDTO(companies);
애초에 mapper class 는 하나로만 관리할 예정이라 ''CompanyMapper 로 수정하였습니다!

2023-10-07 09:52 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/detail/CompanyDetailRepository.java
> +
일단 인터페이스 파일 이름을 `CompanyRepository` 을 바꾸고 `findAll` 이 아닌 `findSortedCompanies` 로 변경했습니다!

2023-10-07 09:53 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/dto/detail/CompanySelectResponse.java
> +public record CompanySelectResponse(
`SortedCompanyResponse` 로 다시 명명했는데 혹시 이 이름은 어떨까요?

2023-10-07 09:59 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/detail/CompanyDetailRepositoryImpl.java
> +    public List<Company> findAllCompanies(CompanySelectRequest request) {
제 생각은 당장은 성능보단 코드양이 주는 부분이 더 장점이 크다고 생각해서 어차피 mapping 은 필요한
부분만 해주니깐 그대로 가는건 어떨까요?

2023-10-08 02:56 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/detail/CompanyDetailRepositoryImpl.java
> +        }
enum class 를 활용하여 가독성 좋게 바꾸었습니다~

2023-10-08 14:10 UTC, ldk980130 requested changes
조금 더 개선할 수 있는 부분이 있어서 코드를 작성해봤어요. 확인해주시고 적용해보면 좋을 것 같아요~

2023-10-08 14:10 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
> +        String sortValue = sort.orElse("id");
``` java
    @GetMapping(value = "companies")
    public ResponseEntity<List<SortedCompanyResponse>> findAllCompanies(
            @ModelAttribute PagingParams params,
            @RequestParam(defaultValue = "companyId") String sort) {

        SortedCompanyRequest request = new SortedCompanyRequest(params.getCursor(), params.getSize(), sort);
        List<SortedCompanyResponse> responses = companyService.findAllCompanies(request);

        return ResponseEntity.ok(responses);
    }
```
`@RequestParam`의 `defalutValue`를 사용하면 기본값을 설정할 수 있습니다

2023-10-08 14:10 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        return companyMapper.toAllSelectDTO(companies);
이름을 `SortedCompanyResponse`로 바꿨으니 이 메서드 이름도 바뀌면 좋을 것 같아요!

2023-10-08 14:10 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/dto/find/SortedCompanyResponse.java
> +        Long id,
노션의 api 스펙은 `companyId`입니다. 스트링 값이 다르면 프론트에서 값을 받아오지 못할거에요

2023-10-08 14:10 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/find/CompanyFindRepositoryImpl.java
> +    }
`switch case` 문도 결국은 `if-else`와 같은 문제를 가지고 있죠. 정렬 기준이 바뀌는 일이 생기면 계속 이 메서드 내용이 바뀔거에요. 정렬 기준을 어떻게 선정하는지에 대해서는 이 메서드의 관심사에선 조금 벗어나는 것 같아요. `SortField`를 더 활용해서 아래와 같이 코드를 개선할 수 있어요.

``` java
@Getter
public enum CompanySortField {
    ESTABLISHMENT_DATE("establishmentDate", company.establishmentDate),
    SALES("sales", company.sales),
    ID("companyId", company.id);

    private final String sort;
    private final ComparableExpressionBase<?> orderExpression;

    CompanySortField(String sort, ComparableExpressionBase<?> orderExpression) {
        this.sort = sort;
        this.orderExpression = orderExpression;
    }

    public static CompanySortField from(String sortValue) {
        return Arrays.stream(values())
                .filter(companySortField -> companySortField.sort.equals(sortValue))
                .findAny()
                .orElse(CompanySortField.ID);

    }

}
```

``` java
    @Override
    public List<Company> findSortedCompanies(SortedCompanyRequest request) {
        CompanySortField companySortField = CompanySortField.from(request.sort());
        return jpaQueryFactory.selectFrom(company)
                .where(getCursorCondition(request.cursor(), company.id))
                .orderBy(companySortField.getOrderExpression().desc())
                .limit(request.size())
                .fetch();
    }

```
그리고 회사에 대한 정렬 기준을 표현하는 `Enum`이니까 이름은 `CompanySortFiled`로 변경하면 어떨까요? 그리고 dto도 아니기 때문에 dto 패키지가 아닌 repository 패키지 밑으로 옮기면 좋을 것 같아요. DB 쿼리에 사용할 정렬 조건을 반환하는 친구니까요

2023-10-10 01:41 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
> +        String sortValue = sort.orElse("id");
감사합니다^^

2023-10-10 01:41 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        return companyMapper.toAllSelectDTO(companies);
아 그렇네요!

2023-10-10 01:42 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/dto/find/SortedCompanyResponse.java
> +        Long id,
넵 수정하겠습니다.

2023-10-10 01:47 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/find/CompanyFindRepositoryImpl.java
> +    }
와.. 정말 깔끔해지네요... 감사합니다.

2023-10-10 04:15 UTC, ldk980130 approved these changes
코드 변경된거 확인해주시고 문제 없으면 머지해주세요~

2023-10-10 04:15 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/find/CompanySortField.java
> +    };
cursor 마다 쿼리의 where 조건문이 다르게 나가야하는데 저도 놓치고 있었네요. 

정렬조건이 기본 id인 경우에눈 쿼리를 짤 때 그냥 c1.id > c2.id비교를 해주면 되지만 slae인 경우에는 c1.sales > s2.sales를, establishmentDate인 경우에는 c1.establishment_date > c2.establishment_date를 해줘야해요. 

Enum의 추상 클래스와 오버라이딩을 사용해서 분기문 없이 이를 처리하도록 코드를 구성했습니다.

2023-10-11 07:22 UTC, merged