Feature/company growth
HANIUM-GROWUP/growthmate-be pull request #27
Opened 2023-10-17 07:51 UTC by Jeongh00

## 📌 작업 내용
기업 성장 예측 그래프 조회 api 입니다.

## 📝 리뷰 요청
개발 진행 시 특이사항은 따로 없었고, 리뷰 진행 부탁드립니다^^

2023-10-17 10:01 UTC, ldk980130 requested changes
고칠게 크게 없습니다! 피드백 드린것만 간단하게 수정하면 바로 approve해도 될 것 같아요. 

다만 `sales` 칼럼의 타입이 정확히 아직 확실하지 않아서 목요일 회의 때 확정 받고 바로 머지시키면 좋을 것 같습니다ㅎ

2023-10-17 10:01 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
> +            );
모두 조회에서 개수 뿐만 아니라 내부 값 확인 👍

2023-10-17 10:01 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/company/domain/CompanyGrowth.java
> +    private Double sales;
`sales`의 데이터 타입을 정확히 확정한 다음에 머지하는게 좋을 것 같네요. 정수인지 `double`인지 아직 확실하지 않으니..

2023-10-17 10:01 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/growth/CompanyGrowthRepositoryImpl.java
> +    }
년도별로 정렬해서 클라이언트에 전달하는게 좋을 것 같아요! `order by year`을 시켜주면 어떨까요?

2023-10-18 02:47 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/growth/CompanyGrowthRepositoryImpl.java
> +    }
추가했습니다 ~

2023-10-18 06:35 UTC, ldk980130 approved these changes
확인했습니다~

2023-10-18 06:42 UTC, merged