feature : 언론 감정 분석 & 긍부정 뉴스 목록 API
HANIUM-GROWUP/growthmate-be pull request #31
Opened 2023-10-27 07:00 UTC by Jeongh00

## 📌 작업 내용
언론 감정 분석 api , 언론 긍부정 뉴스 목록 api 작업 같이 진행했습니다.

## 📝 리뷰 요청
비슷한 기능의 api 들이라 특이사항은 딱이 없었습니다^^.
리뷰 부탁드립니다 ~

2023-10-27 10:17 UTC, ldk980130 requested changes
구현 빠르게 해주셨네요! 수고하셨습니다. 그런데 구현부에서 어색한 점들이 몇몇 보여서 코멘트 남겼어요. 확인해 보시고 고쳐주세요! 그리고 구현이 잘되어 있는지 테스트를 좀 더 꼼꼼하게 하면 좋을 것 같습니다~

2023-10-27 10:17 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +    }
없는 회사 ID로 조회하게 되면 예외가 발생하는 것이 아닌 null을 반환하게 되고 클라이언트는 null을 받지만 상태코드 200을 받네요. 예외처리가 필요하지 않을까요?

2023-10-27 10:17 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/mapper/CompanyNewsMapper.java
> +        );
api 스펙에 따르면 `projection.getCompanyId()`가 아닌 `projection.getId()`가 되어야하지 않을까요? 필요한게 companyNewsId니까요
``` java
public record CompanyNewsResponse(Long companyNewsId,
                                  String title,
                                  String description,
                                  String url,
                                  Sentiment sentiment) {
}
```

2023-10-27 10:17 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/news/CompanyNewsRepositoryImpl.java
> +                .fetch();
갑자기 `post.id`가 튀어나왔는데 `companyNews.id`여야하는 것 아닐까요? 커서 페이징 잘 되던가요? 테스트가 필요하겠네요.

2023-10-27 10:17 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/news/CompanyNewsRepositoryImpl.java
> +}
뉴스 목록 쿼리를 보니 정렬 조건을 명시해주지 않았네요. 그럼 id 순정렬이라 1, 2, 3, 4... 순서로 조회될거에요. 그런데 커서 페이징 쿼리 조건을 커서보다 작은 값 (less then)이면 마지막 커서 기준 다음 값이 안나오지 않을까요? id 순정렬이면 `gt`(greater than)이어야 할 것 같아요. 아니면 id역정렬을 한뒤 `lt`를 쓰던가요.

저도 헷갈리는 걸 수도 있으니 테스트를 해서 커서페이징이 잘 되는지 확인하면 좋을 것 같아요!

2023-10-27 10:17 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/news/projection/CompanyNewsProjection.java
> +            );
프로젝션을 할 때 companyNews의 ID를 가져와야할 것 같아요! 커서에 쓰여야 하니까요. companyId는 where 조건에 사용되는 친구입니다~

2023-10-27 10:17 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
> +        }
커서 페이징이 잘 되는지 커서 다음에 목록이 잘 조회되는지도 검증해주세요! 구현 부분에서 어색한 부분들이 보여서 체크가 필요할 것 같습니다 😄

2023-10-30 02:04 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/mapper/CompanyNewsMapper.java
> +        );
수정했습니다^^

2023-10-30 02:05 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/news/CompanyNewsRepositoryImpl.java
> +                .fetch();
수정했습니다^^

2023-10-30 02:06 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/news/projection/CompanyNewsProjection.java
> +            );
수정했습니다^^

2023-10-30 03:57 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +    }
메서드 분리하여 처리했습니다^^

2023-10-30 05:16 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/repository/news/CompanyNewsRepositoryImpl.java
> +}
그렇네요.. 밑에 테스트 달아주신거랑 같이 포함해서 수정 모두 완료했습니다^^

2023-10-30 14:11 UTC, ldk980130 requested changes
리뷰 반영 수고하셨습니다! 예외 처리 관련해서 딱 1가지만 피드백 드렸는데 이것만 고치면 approve 하면 될것 같습니다. 간단한거라서 금방 고칠 수 있을거에요~

2023-10-30 14:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +    }
> 없는 회사 ID로 조회하게 되면 예외가 발생하는 것이 아닌 null을 반환하게 되고 클라이언트는 null을 받지만 상태코드 200을 받네요. 예외처리가 필요하지 않을까요?

없는 회사 ID라는게 `companyId`가 `null`인 경우를 말하는 것이 아니라 존재하지 않는 회사 ID로 조회하는 경우를 말하는 거였어요. 아래 스크린샷 처럼 PK가 1번인 회사가 존재하지 않으니 원래는 예외가 발생해야 하지만 200 OK를 보내주고 있는 것을 확인할 수 있어요.
<img width="1425" alt="image" src="https://github.com/HANIUM-GROWUP/growthmate-be/assets/78652144/59f0cbaa-676c-45d6-8680-dc26af8d9e7b">

`companyId`가 `null`인 경우는 고려하지 않아도 될 것 같아요. 저 값이 비어버리면 아예 url 매핑이 안되서 400에러가 발생하거든요

다른 api에서 구현했던 것처럼 Optional을 활용하면 처리할 수 있을거에요
``` java
    public CompanyAnalysisResponse findCompanyAnalysis(CompanyAnalysisRequest request) {

        Optional<CompanyAnalysis> entityResponse = Optional.ofNullable(companyRepository.findCompanyAnalysis(request));

        return entityResponse
                .map(companyMapper::toAnalysisDTO)
                .orElseThrow(() -> new BusinessException(CompanyException.NO_FOUND_COMPANY.getHttpStatusCode(), CompanyException.NO_FOUND_COMPANY.getMessage()));
    }
```

2023-10-30 14:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        if (request.companyId() == null) throw throwCompanyNotFoundException();
여기도 `comapnyId`에 대한 `null` 검사를 굳이 하지 않아도 됩니다. 애초에 /companies/300/news 이런 형태에서 중간에 id가 없으면  이 메서드를 만날 수 조차 없습니다. url 매핑이 안되거든요.

2023-10-30 14:11 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
> +        }
테스트가 있으니 마음이 편안해지네요 😄

2023-10-31 01:08 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +    }
아 제가 잘못 이해했었네요. 확인했고 모두 수정 반영했습니다^^

2023-10-31 03:38 UTC, ldk980130 requested changes
approve 하고 싶은데 한 번더 짚고 넘어가야할 것 같아서 다시 RC 드립니다.

프로그래밍을 하다보면 `null`을 다뤄야할 때가 많은데요. `null`이 있으면 NPE가 나서 개발자가 예상치 못한 예외를 발생시킬 수도 있어 개발자는 `null`을 잘 다뤄야 하죠.

메서드에서 `null`을 반환하는 건 그 메서드를 쓰는 클라이언트 쪽에서 `null`이 올 거란 위험을 안고 개발해야 하기 때문에 `null` 그 자체를 반환하는건 특별한 이유가 있지 않고선 지양해야 한다고 생각해요.

그래서 코틀린에서는 nullable이라는 개념을 도입하고 자바에선 `Optional`로 `null`을 더 안전하게 다루도록 하고 있죠. 그래서 '단건' 조회인 경우 `Optional`을 반환하도록 메서드 api를 설계하면 메서드를 사용하는 쪽에서 `Optional`의 다양한 기능을 사용해 `null`을 잘 처리할 수 있습니다.

그럼 모든 메서드의 반환은 `Optional`이어야 할까요? 사실 중요한건 `null`을 반환하지 않도록 하는 것이기 때문에 어떤 메서드의 결과가 '없다'라는 것을 표현할 수 있다면 `Optional`일 필요는 없어요. 대표적으로 컬렉션 객체들이 있죠. 컬렉션들은 여러 객체들을 담고 있는 객체기 때문에 그냥 빈 컬렉션을 반환하면 `Optional`이 아니더라도 `null`이 아니더라도 '없다'라는 것을 표현할 수 있어요. 실제로 Spring Data JPA에선 `List`를 반환하는 경우 조회 결과가 없다면 빈 리스트를 반환하고 있어요.

빈 리스트를 반환할 수 있는데 굳이 `Optional`을 쓸 필요가 없다고 생각해요. 코드는 가능한 필요 없는 코드를 넣지 않고 필요한 부분만 넣어서 개발하는게 좋습니다.

2023-10-31 03:38 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        Optional<List<CompanyGrowthProjection>> entityResponse = Optional.ofNullable(companyRepository.findCompanyGrowth(companyId));
`List`를 `Optional`로 감싼 건 어떤 상황을 전제한 것일까요? `List`가 `null`인 경우가 있을까요?

2023-10-31 03:38 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        Optional<List<CompanyNewsProjection>> entityResponseOptional = Optional.ofNullable(companyRepository.findCompanyNewsList(request));
여기도 마찬가지로 `List`가 `null`인 경우가 있을까요? 물론 이렇게 해도 동작하는데는 문제 없겠지만 필요 없는 코드가 늘어나면 나중에 코드가 복잡해질 수가 있을 것 같아요.

2023-10-31 04:22 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
> +        Optional<List<CompanyGrowthProjection>> entityResponse = Optional.ofNullable(companyRepository.findCompanyGrowth(companyId));
코멘트 달아주신거 잘 확인했습니다. 아래 케이스까지 모두 수정 완료했습니다!

2023-10-31 04:24 UTC, ldk980130 approved these changes
수고하셨습니다!

2023-10-31 06:01 UTC, merged