Feature/login
HANIUM-GROWUP/growthmate-be pull request #6
Opened 2023-08-15 03:34 UTC by Jeongh00

1. 로그인 기능
2. 회원 정보 수정 기능
3. 회원 정보 조회 기능

-> 총 3가지에 대해 한번에 작업 진행했습니다.
너무 많은 파일들을 작업하다 보니 놓친 부분들이 많이 있을 것 같습니다. 코드 리뷰 부탁드립니다^^

2023-08-17 07:11 UTC, ldk980130 requested changes
일단 인증 관련된 부분만 리뷰 남겨놓았어요. 회원 부분은 인증 부분을 완료하고 나서 리뷰해드릴게요!

테스트가 돌아가지 않던데 이건 로컬 DB 연결 설정은 mysql로 해놔서 그럴거에요. 로컬 DB 연결을 H2가 아닌 mysql로 해놓은 이유가 있을까요? 로컬에서 실행할 때나 테스트를 돌릴 때마다 도커 등을 켜야해서 번거로울 것 같아요.

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
jdbc 의존성이 필요한가요? jpa 의존성만 가져오면 DB 접근이 가능할 것 같은데 있어야하는 이유가 있을까요?

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/build.gradle
> +    runtimeOnly 'com.mysql:mysql-connector-j'
core 모듈에 mysql 의존성이 있어서 api 모듈에는 추가하지 않았었는데 api 모듈에도 mysql 의존성이 필요할까요? DB 관리는 core 모듈에서 전담하면 어떨까요? 필요하면 core 모듈에 운영 환경 DB 설정을 관리하는 yml이 필요해질 수도 있지만요.

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/OAuthLoginFailureHandler.java
> +        response.sendRedirect(redirectUrl + "/?errorCode=" + oAuth2Error.getErrorCode());
`redirectUrl + "?errorCode=` 이렇게 `/` 없이 쿼리스트링을 바로 전달하면 되지 않나요? 저도 예전 프로젝트에서오타를 냈었네요.

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/OAuthLoginSuccessHandler.java
> +        response.addHeader(ACCESS_TOKEN, oauth2Member.getAccessToken());
https://ko.wikipedia.org/wiki/JSON_%EC%9B%B9_%ED%86%A0%ED%81%B0

>  일반적으로 Bearer 스키마를 사용하여 Authorization 헤더 안에 JWT를 보내야 한다.

JWT 토큰을 헤더에 담아 보낼 때는 Autorization 헤더에 Bearer 형식으로 보내는 것이 일반적이라고 알고 있어요.

`Authorization: Bearer eyJhbGci...`

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/PrincipalOAuth2UserService.java
> +            OAuth2Error oAuth2Error = new OAuth2Error(String.valueOf(500));
`BusinessException` 자신이 상태 코드를 알고 있으니 그대로 전달하면 되지 않을까요? 무조건 500에러는 아닌 것 같아요!

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
> +    private static final String SECRET_KEY = "SGFuRXVtIEdyb3d0aE1hdGUgQmFja2VuZCBSYW5kb20gRW5jb2RpbmcgU2VjcmV0IEtleQ==";
시크릿키를 직접 명시해준걸까요? yml에 있는 시크릿키를 받아오려면 `${...}` 형식으로 되어있어야하는 것 아닐까요?

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
> +    private static final String EXPIRE_LENGTH = "86400"; // 24 * 60 * 60 (하루)
만료기간은 코드 내에 직접 명시하는 방식으로 한걸까요 아니면 이것도 yml에서 받아오려고 했던걸까요?

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/config/SecurityConfig.java
> +package com.growup.growthmate.config;
사소한거긴한데 spring security 관련 코드가 쓰인 것은 security 패키지 내부로 옮기면 어떨까요? 시큐리티 관련 코드를 건드려야 한다면 해당 패키지 내부만 들여다보면 돼서 편할 것 같아요!

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +    password: 1234
flyway가 안된 원인이 이거일거라 생각돼요. 로컬 환경에서는 H2 인메모리 DB를 그대로 사용하면 될텐데 여기서도 mysql로 연결하는 이유는 무엇인가요? 도커 등으로 mysql을 띄우지 않으면 로컬에서 실행이 안되네요.

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +          auto: create
DB 마이그레이션으로 flyway를 사용할거기 때문에 none으로 설정해주시면 됩니다!

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +      secret-key: SGFuRXVtIEdyb3d0aE1hdGUgQmFja2VuZCBSYW5kb20gRW5jb2RpbmcgU2VjcmV0IEtleQ==
이 시크릿키는 로컬용으로 하고 운영용 시크릿키는 나중에 application-prod.yml에 새로 만들면 될 것 같습니다

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +class AuthServiceTest {
DB를 접근하는 테스트라면 `@TestIsolation`도 달아주시면 테스트 환경이 격리될겁니다!

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +    }
이 테스트의 의도는 무엇인가요?

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +    }
이 테스트는 이 테스트만 실행하면 실패할 테스트네요. 테스트는 혼자 실행시키든 다른 테스트랑 같이 실행시키든 결과가 똑같아야 합니다. 하지만 이 테스트는 다른 테스트에서 가입된 사용자를 넣어줘야 통과하는 테스트가 되었어요. 어떻게 하면 이 테스트가 완전해질 수 있을까요?

2023-08-17 07:11 UTC, ldk980130 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +}
파일 끝에 개행 추가해주세요!

2023-08-21 08:45 UTC, Jeongh00 commented on growthmate-api/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
아 mybatis 사용이 없기때문에 필요없을 것 같네요. 수정하겠습니다^^

2023-08-21 08:46 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/OAuthLoginFailureHandler.java
> +        response.sendRedirect(redirectUrl + "/?errorCode=" + oAuth2Error.getErrorCode());
그러게요...ㅎㅎ 수정하겠습니다^^

2023-08-21 08:49 UTC, Jeongh00 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +class AuthServiceTest {
아하 넵! 수정 반영하겠습니다!!

2023-08-21 08:50 UTC, Jeongh00 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +    }
아 시크릿 키가 잘 만들어지는지 테스트 해본 용도였습니다. 필요없는 코드인 것 같아 지우겠습니다~

2023-08-21 23:55 UTC, Jeongh00 commented on growthmate-api/build.gradle
> +    runtimeOnly 'com.mysql:mysql-connector-j'
하위 모듈인 core 모듈에만 의존성이 들어있으면 될 것 같네요. 삭제하겠습니다^^

2023-08-21 23:56 UTC, Jeongh00 commented on growthmate-api/src/main/resources/application-local.yml
> +      secret-key: SGFuRXVtIEdyb3d0aE1hdGUgQmFja2VuZCBSYW5kb20gRW5jb2RpbmcgU2VjcmV0IEtleQ==
넵 알겠습니다. 후에 application-prod.yml 파일에도 운영 용으로 새로 만들겠습니다.

2023-08-22 00:53 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/OAuthLoginSuccessHandler.java
> +        response.addHeader(ACCESS_TOKEN, oauth2Member.getAccessToken());
아 그렇네요. token type 을 넣어주지 않았네요. 추가하겠습니다!

2023-08-22 00:57 UTC, Jeongh00 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +}
넵 알겠습니다.

2023-08-22 05:17 UTC, Jeongh00 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +    }
근데 테스트의 목적 자체가 가입된 사용자에 대한 체크 용도라서 필요한 부분이라고는 생각합니다. 그럼 @BeforeEach 로 given 부분을 넣어놓고 하는 방법은 어떨까요?? 아니면 혹시 다른 방법이 있으신가요??

2023-08-22 05:39 UTC, Jeongh00 commented on growthmate-api/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
> +    }
login 메서드 안에서 현재 회원가입과 로그인을 함께 진행하게끔 되어있어서 이 테스트는 따로 가입자를 넣어줘야 통과하는 테스트는 아니라서 단위 테스트가 맞는 것 같습니다. 하지만, 좀 더 직관적으로 보이면 좋을 것 같아서 메서드 이름을 signUpAndLogin 으로 바꿔주면 더 좋지 않을까 생각합니다.

2023-08-22 06:56 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/PrincipalOAuth2UserService.java
> +            OAuth2Error oAuth2Error = new OAuth2Error(String.valueOf(500));
아 그렇네요.. exception 에서 errorCode 받아서 처리하도록 수정하겠습니다!!

2023-08-22 08:56 UTC, merged