로그인, 회원 정보 조회 및 수정 API 1차 수정본
HANIUM-GROWUP/growthmate-be pull request #8
Opened 2023-08-22 23:59 UTC by Jeongh00

1차 코드리뷰 주신 것 반영 완료했습니다~
Member 쪽 리뷰 아직 진행 안된 상태라 리뷰 부탁드립니다^^

2023-08-23 05:57 UTC, ldk980130 requested changes
좀 더 걸릴 것 같긴한데 이번에도 '회원'쪽은 아직 리뷰 못했습니다. 한 번에 많은 리뷰를 남기면 복잡해질 것 같아서요. 이번에도 '인증' 부분에만 리뷰 남겼습니다. 변경해야할 점이나 질문 그리고 생각해볼만한 점 등을 남겨보았습니다. 이 리뷰들만 잘 고치면 '회원'쪽 리뷰로 넘어갈 수 있을 것 같아요. 좀 힘들 수도 있지만 피드백 반영 잘 부탁드립니다!

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/LoginMemberResolver.java
> +                .orElseThrow();
이 부분을 그냥 예외를 던지면 `NoSuchElementException`이 발생할 겁니다. 이 예외를 잡는 핸들러가 없기에 클라이언트는 500에러를 받게 될텐데 토큰이 없는 경우는 500(서버 잘못)이 아니라 400 에러를 넘겨줘야하지 않을까요? `BusinessException`을 사용해서 `GlobalExceptionHandler`이 잡을 수 있는 예외를 던져주세요!

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/OAuthLoginSuccessHandler.java
> +        response.addHeader(AUTHORIZATION, "Bearer " + oauth2Member.getAccessToken());
👍

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/PrincipalOAuth2UserService.java
> +    }
'인증' 부분에선 Spring Security를 사용하다보니 `PrincipalOAuth2UserService`가 Controller의 역할을 하는 것처럼 보이네요. 그리고 서비스 계층인 `AuthService`를 사용하고 있습니다. 이렇게 보니 AuthService가 api 모듈에 있는 것이 자연스러운지 의문이 드는 것 같아요. api 모듈에서는 security 관련한 코드와 엔드포인트와의 상호작용만 담당하고 `AuthService`와 다른 토큰 관련 비즈니스 로직은 core 모듈로 가는 게 자연스럽지 않은가 생각이 듭니다. 이 부분은 어떻게 생각하시나요?

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authoriization/UnAuthorizationEntryPoint.java
> +        writer.println(objectMapper.writeValueAsString(MemberException.AUTHORIZATION_FAIL));
`MemberException.AUTHORIZATION_FAIL`는 enum 상수인데 직렬화하면 어떻게 되던가요?

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
> +    }
이렇게 지정해버리면 yml 파일에서 시크릿키랑 만료시간을 못가져오지 않을까요? 어떻게 해야 yml에 있는 값을 가져오도록 변경할 수 있을까요?

만약 yml에 있는 값을 사용하지 않고 이렇게 하드 코딩해놓으면 두 가지 문제점이 발생할 것 같아요.
1. 토큰의 비밀 키가 깃허브에 노출된다.
2. 토큰 비밀키 또는 만료시간을 변경하려고 하면 파일을 변경하고 커밋하고 푸시하고 머지시키는 과정이 필요하다. (yml에 비밀키랑 만료시간을 관리한다면 yml 파일만 변경하고 배포 스크립트만 다시 실행하면 된다.)

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/java/com/growup/growthmate/config/SecurityConfig.java
> +public class SecurityConfig {
Spring Security 관련된 코드는 security 패키지 내부에 옮기면 어떨까요? 그럼 spring security 관련 변경 사항은 그 패키지만 뒤지면 되서 관리하기 편할 것 같아요!

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +
로컬에서도 mysql에 연결하려고 하니 mysql이 없거나 도커로 띄우지 않는 한 테스트가 안돌아가고 실해도 되지 않습니다. 제가 해놓은대로 h2를 로컬에서 사용하면 더 편할 것 같은데 로컬에서도 mysql로 연결하려는 이유가 있을까요?

2023-08-23 05:57 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +          auto: create
flyway를 사용하고 있으니 none으로 바꿔주세요!

2023-08-23 06:13 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/config/SecurityConfig.java
> +public class SecurityConfig {
넵! 패키지 이동시키겠습니다^^

2023-08-23 06:15 UTC, Jeongh00 commented on growthmate-api/src/main/resources/application-local.yml
> +
따로 이유는 없고, docker-compose 파일을 local 버전과 상용 버전 두 가지로 분리해서 작업하느라 그렇게 설정해 두었습니다. h2 로 사용하면 더 편할 것 같네요. h2 로 수정반영하겠습니다.

2023-08-23 07:10 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/LoginMemberResolver.java
> +                .orElseThrow();
BusinessException 을 통해 400 에러로 수정 완료했습니다!

2023-08-23 07:38 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
> +    }
아 수정하려고 했었는데 이 부분은 놓쳤네요^^.
'${}' 방식으로 프로퍼티 확장을 통해 외부 환경에 의해 설정되도록 수정할 예정입니다.

2023-08-23 08:19 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +
아 이건 제가 실수한 부분인 것 같은데요
<img width="330" alt="image" src="https://github.com/HANIUM-GROWUP/growthmate-be/assets/78652144/67c61923-147e-4248-939d-ae2ae94eb91f">
common 모듈의 textFixture 패키지에 패키지 구조를 위와 같이 잡으면 해결됩니다!

2023-08-23 08:19 UTC, ldk980130 commented on growthmate-api/src/main/resources/application-local.yml
> +
모든 모듈에서 패키지 구조를 com.growup.growthmate로 시작되도록 되어 있는지 잘 살펴봐야겠네요

2023-08-24 02:19 UTC, Jeongh00 commented on growthmate-api/src/main/resources/application-local.yml
> +
말씀주신대로 수정하니깐 잘 켜지네요. h2 로 수정 반영했습니다^^.

2023-08-24 02:40 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/PrincipalOAuth2UserService.java
> +    }
듣고보니 그게 더 자연스러울 것 같아요. 저도 이전 프로젝트에서 그렇게 작업했던 기억이 있네요. `AuthService` 파일과 `MemberOauthRepository` 파일, 연결된 token 파일들과 연결된 dto 파일들 core 모듈로 이동하도록 하겠습니다.

2023-08-24 04:28 UTC, Jeongh00 commented on growthmate-api/src/main/java/com/growup/growthmate/auth/security/authoriization/UnAuthorizationEntryPoint.java
> +        writer.println(objectMapper.writeValueAsString(MemberException.AUTHORIZATION_FAIL));
enum 상수가 JSON 문자열로 변환되면 "AUTHORIZATION_FAIL" 로 출력되는 것으로 알고 있습니다^^.

2023-08-25 05:13 UTC, ldk980130 requested changes
인증은 어느정도 마무리가 된 것 같고 회원쪽 리뷰 남겼습니다.

yml 파일이 현재는 전부 api 모듈에서 관리되고 있는데요. core가 필요한 값은 core의 yml에서 관리하는 식으로 나중에 따로 브랜치를 파서 개선할까 합니다. 일단 지금은 이렇게 진행하면 될 것 같아요.

그리고 예전에 얘기 나눴던 명령 로직과 조회 로직의 분리, 그리고 api 모듈의 패키지 구조에 대해서는 비대면 회의를 통해 따로 얘기해보도록 해요. 현재 api 모듈 내 패키지 구조가 통일되어 있지 않아서 논의가 필요할 것 같아요. 그건 다음에 직접 대화하면서 풀어보도록 하고 일단 코드적인 것만 리뷰 남겼습니다.

마지막까지 화이팅~~

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
core 모듈에는 시큐리티, ouaht2, web 의존성은 필요없지 않나요?

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
> +            return false;
잘못된 토큰 값이 들어오믄 `MalFormedJwtException`이 발생하기에 해당 예외도 추가해두었습니다.

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/application/MemberService.java
> +    }
사소한 거긴한데 검증 메서드를 다른 메서드로 추출하면 더 가독성이 좋아질 것 같아요!
``` java
    @Transactional
    public Member join(MemberRequest request) {
        validateDuplicateEmail(request.email());
        return memberRepository.save(request.toEntity());
    }

    private void validateDuplicateEmail(String email) {
        MemberException duplicated = MemberException.MEMBER_DUPLICATE_EMAIL;
        if (memberRepository.existsByEmail(email)) {
            throw new BusinessException(duplicated.getHttpStatusCode(), duplicated.getMessage());
        }
    }
```

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/application/MemberService.java
> +    }
클래서 최상단에 `@Transactional(readOnly=true)`가 있으니 이 메서드에 또 `@Transactional`을 붙이지는 않아도 될 것 같아요.

그리고 해당 memberId에 해당하는 사용자가 없을 수도 있는데 그거에 대한 예외처리가 빠져있네요. Optional의 메서드 체이닝을 이용하여 아래와 같이 구현할 수도 있습니다.
``` java
public MemberInfoResponse getMemberInfo(Long memberId) {
        return memberRepository.findById(memberId)
                .map(member -> new MemberInfoResponse(member.getName(), member.getEmail(), member.getPictureUrl()))
                .orElseThrow(() -> new BusinessException(
                        MemberException.NO_FOUND_NAME.getHttpStatusCode(),
                        MemberException.NO_FOUND_NAME.getMessage())
                );
    }
```

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/application/MemberService.java
> +        return member;
이런 경우 웬만하면 바로 리턴하는 방식을 사용하면 코드가 더 짧아지고 깔끔해집니다.
``` java
    private Member getMember(MemberUpdateInfoRequest memberUpdateInfoRequest) {
        MemberException notFound = MemberException.NO_FOUND_NAME;
        return memberRepository.findById(memberUpdateInfoRequest.memberId())
                .orElseThrow(() -> new BusinessException(notFound.getHttpStatusCode(), notFound.getMessage()));
    }
```

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/domain/Member.java
> +    }
이름 수정 유스케이스에 아래와 같은 규칙이 있어요.
<img width="714" alt="image" src="https://github.com/HANIUM-GROWUP/growthmate-be/assets/78652144/c089391e-fd30-459d-b20c-6c5fac405fe7">

위 검증 로직을 추가하고 테스트도 추가되어야할 것 같습니다!

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/domain/Member.java
> +}
개행 추가해주세요!

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/exception/MemberException.java
> +    NO_FOUND_NAME(404, "존재하지 않는 회원입니다."),
회원이 존재하지 않는다는 예외니까 `NOT_FOUND_MEMBER`가 자연스럽지 않을까요?

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/main/resources/db/migration/V1__init.sql
> +    registration_id VARCHAR(255)          NULL,
NULL 보단 NOT NULL이 더 나을 것 같아요!

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/test/java/com/growup/growthmate/member/application/MemberServiceTest.java
> +            assertThat(member.getName().equals(NEW_NAME));
검증이 되고 있지 않네요. 뒤에 `.isEqualTo(...)`를 붙여주세요!

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/test/java/com/growup/growthmate/member/application/MemberServiceTest.java
> +            assertThat(member.getPictureUrl().equals(response.picture()));
전부 isEqualTo 검증이 빠져있어요!

2023-08-25 05:13 UTC, ldk980130 commented on growthmate-core/src/test/java/com/growup/growthmate/member/application/MemberServiceTest.java
> +}
개행 추가해주세요~

2023-08-27 11:28 UTC, Jeongh00 commented on growthmate-core/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
그렇네요. 수정하겠습니다!

2023-08-27 12:52 UTC, Jeongh00 commented on growthmate-core/src/main/java/com/growup/growthmate/member/exception/MemberException.java
> +    NO_FOUND_NAME(404, "존재하지 않는 회원입니다."),
그게 더 좋을 것 같네요^^

2023-08-28 01:05 UTC, Jeongh00 commented on growthmate-core/src/main/java/com/growup/growthmate/member/application/MemberService.java
> +    }
더 깔끔해졌네요^^. 감사합니당~

2023-08-28 04:08 UTC, Jeongh00 commented on growthmate-core/src/test/java/com/growup/growthmate/member/application/MemberServiceTest.java
> +            assertThat(member.getPictureUrl().equals(response.picture()));
equals 로 검증하면 된다 생각했는데, asserThat 안에서 equals 검증은 안 좋은 방법인가요? 일단 asserThat 밖에서 isEqualTo 호출로 모두 수정하겠습니다.

2023-08-28 05:58 UTC, ldk980130 commented on growthmate-core/src/test/java/com/growup/growthmate/member/application/MemberServiceTest.java
> +            assertThat(member.getPictureUrl().equals(response.picture()));
뒤에 `isEqualTo()` 같은 검증 메서드를 붙여주지 않으면 검증이 되지 않습니다. `assertThat()` 안에서 `equals()` 안에 다른 문자열을 넣어도 테스트는 통과할 겁니다.

2023-08-28 07:52 UTC, Jeongh00 commented on growthmate-core/src/main/java/com/growup/growthmate/member/domain/Member.java
> +    }
`@Length` 어노테이션으로 검증 추가했고, Spring Validation 을 이용한 테스트 도 추가 완료했습니다 ~

2023-08-28 10:34 UTC, ldk980130 approved these changes
기나긴 로그인, 회원 정보 및 수정 api 수정본 피드백 반영하느라 수고하셨습니다. 마지막에 몇 가지 생각해 볼 점을 남겼는데요. merge하기 전에 한 번 생각해보고 merge하면 좋겠습니다.ㅎㅎ

2023-08-28 10:34 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/domain/Member.java
> +    private String name;
이런식으로 hibernate 애너테이션으로 검증하는 것도 방법이긴 합니다. 하지만 이 방식을 선택하면 Member를 대상으로 하는 단위 테스트에서 스프링 컨테이너를 띄어야하는 단점이 생겨요. 보통 순수 도메인 로직은 자바 코드만으로 작성되고 자바 코드만을 대상으로 테스트하기에 단위 테스트는 빠르다라는 장점을 가지는 건데요. 이렇게 특정 프레임워크에 의존하는 로직을 쓰는 것에 대해서는 한 번 생각해볼 필요는 있을 것 같아요.

2023-08-28 10:34 UTC, ldk980130 commented on growthmate-core/src/main/java/com/growup/growthmate/member/domain/Member.java
> +    @Builder
이 빌더는 테스트 클래스에서만 사용하더라구요. 보통 테스트 코드에서만 사용되는 코드를 프로덕션 코드에 추가하지 않아요. 빌더가 정말 필요한지 다시 한 번 생각해보면 좋을 것 같아요.

2023-08-28 10:34 UTC, ldk980130 commented on growthmate-core/src/test/java/com/growup/growthmate/member/domain/MemberNameTest.java
> +public class MemberNameTest {
앞서도 이미 말했지만 도메인 테스트에서 애플리케이션 컨텍스트를 띄울 필요가 있을까 생각해보면 좋을 것 같아요! 그리고 DB에 접근하는 테스트가 아니기에 TestIsolation은 안붙여도 됩니다.

2023-08-28 10:34 UTC, ldk980130 commented on growthmate-core/src/test/java/com/growup/growthmate/member/domain/MemberNameTest.java
> +        Member member = Member.builder().name(value).build();
@Length 기능을 사용해서 검증을 사용하게 되면 이렇게 잘못된 이름의 `Member`가 생성되어 버리는 것도 단점이네요 👀  실제로 예외가 발생하는 시점은 DB에 접근할 때구요.

2023-08-29 06:55 UTC, merged